### ISSUE TITLE
Is it possible for perfjankie Tool to pull the data from my database ? 

### ISSUE THREAD

**Issue by challapruthvi** [axemclion/protractor-perf#11]
Continuation to #10  

Ok. I will try to write the database connection code . But Will I be able to use perfjankie tool ?

protractor-perf --> SomeDB (couchDB, MongoDB, any possible DB) --> Perfjankie Tool ??

Is the above flow possible ? Especially the last step i.e., Can we use perfjankie Tool to display the dashboard by getting the data from some external DB where I have stored my Metrics Information which I got from protractor-perf ??

**Comment by axemclion** [comment]
Yes, perfjankie can simply be used as a way to display data, it just expects the remote URLs to send it data in a specific format. You would just have to implement [these](https://github.com/axemclion/perfjankie/blob/aee5dd1c8295f7bb422dae6f036fd76c1023f3dd/www/server/endpoints.js#L18) remote URLs.

**Comment by iljapavlovs** [comment]
@axemclion so there`s really no way how to present the stats in readable format "out of the box"?

**Comment by axemclion** [comment]
I initially created protractor-perf to simply use these perf values in assertions. Looks like folks are definitely interested in seeing the actual metrics. I added a `perf.printStats()` methods that logs all the metrics in JSON format on the console. Will this be sufficient? 

@iljapavlovs Are there other ways you are looking to see the data ?

**Comment by iljapavlovs** [comment]
so the problem I see is that protractor-perf is lacking some neat reporter tool with graphical representations and with some way monitor performance trends over time (like the same you have in perfjankie tool - the trend line).

Moreover, I am quite confused with all of those performance metrics - I can`t choose the right one in order to measure Response time from start doing the action till it`s rendered. E.g. user clicks on the button and I want to measure the time till page is rendered completely and all requests are finished.
Are those Navigation Timing metrics? And will those be calculated per one request or for all requests during start/stop timeframe?
Another thing, I can`t understand why execution time is much slower compared running plain protractor test .

**Comment by axemclion** [comment]
To answer some of your questions
1. Technically, the results can be used for perfjankie since they are in the JSON format. I have not done the work for that yet, but I would appreciate a pull request. 
2. I think you would need to define the metric a little better. Are you looking at the firstPaintTime? Are you performing an action and looking for framerate, or do you want to measure the network timing ?
3. The execution of the test itself is not slower, `protractor-perf's` start and stop is the one slowing things down. This is due to the huge amount of logs that `protractor-perf` reads from chrome to collect all the data. It is basically the entire Chrome timeline that is converted to JSON string, parsed and metrics collected. This would be similar to manually opening DevTools to look at the data.

**Comment by axemclion** [comment]
Closing as there is no task on protractor-perf's code.
