### ISSUE TITLE
performance - Java heap space

### ISSUE THREAD

**Issue by david-sosa-valdes** [axemclion/protractor-perf#34]
Hi, when we try to run the performance tests:

```
../node_modules\wd\lib\utils.js:139
  var err = new Error();

Error: [log("performance")] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: Java heap space.
```

Webdriver-manager reports:

```
16:25:30.251 INFO - Executing: [fetching logs for: performance])
16:25:35.648 WARN - Exception thrown
      java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
```

**Comment by axemclion** [comment]
This could happen if the tests run for a very long time and the collected timeline data is huge. Here are some ways to fix this 
1. Increase the Java Heap size 
2. Instead of running selenium, you could try running chromedriver only. I have seen it handle memory much better
3. Reduce the duration of break down your tests into smaller groups
4. Reduce the metrics that you are trying to measure. For example, just measure the time. This can be an option passed to browser-perf.
